[package]
name = "chapter10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mnist.workspace = true
ndarray.workspace = true
ndarray-rand = "0.15.0"
